import { defineRailway, postgres, preserve, project, service } from "railway/iac";

// Railway infrastructure as code. Preview changes with `railway config plan`,
// apply them with `railway config apply`. Railway doesn't read this file
// during deploys; the template (or `config apply`) sets these values.
export default defineRailway(() => {
  // The managed Postgres helper provisions its own volume.
  const db = postgres("Postgres");

  const web = service("web", {
    // Railpack runs `pnpm build`; Nitro outputs a self-contained server.
    start: "node .output/server/index.mjs",
    // Apply Drizzle migrations (and seed an empty board) before each
    // deployment starts. If this fails, the deploy stops.
    preDeploy: "node scripts/migrate.mjs",
    // New deployments only receive traffic once this returns a 2xx.
    healthcheck: "/api/health",
    healthcheckTimeout: 60,
    env: {
      // Private network: postgres.railway.internal, no egress charges.
      DATABASE_URL: db.env.DATABASE_URL,
      // Generated by the template as ${{secret(32)}}; kept as-is here.
      SESSION_SECRET: preserve(),
    },
  });

  return project("tanstack-start-departures", {
    resources: [db, web],
  });
});
