/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ApiDeparturesRouteImport } from './routes/api/departures'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardIdRouteImport } from './routes/board.$id'
import { Route as BoardLiveRouteImport } from './routes/board.live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeparturesRoute = ApiDeparturesRouteImport.update({
  id: '/api/departures',
  path: '/api/departures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/board/$id',
  path: '/board/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardLiveRoute = BoardLiveRouteImport.update({
  id: '/board/live',
  path: '/board/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/stats': typeof StatsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/health': typeof ApiHealthRoute
  '/board/$id': typeof BoardIdRoute
  '/board/live': typeof BoardLiveRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/stats': typeof StatsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/health': typeof ApiHealthRoute
  '/board/$id': typeof BoardIdRoute
  '/board/live': typeof BoardLiveRoute
  '/board': typeof BoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/stats': typeof StatsRoute
  '/api/departures': typeof ApiDeparturesRoute
  '/api/health': typeof ApiHealthRoute
  '/board/$id': typeof BoardIdRoute
  '/board/live': typeof BoardLiveRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/stats'
    | '/api/departures'
    | '/api/health'
    | '/board/$id'
    | '/board/live'
    | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/stats'
    | '/api/departures'
    | '/api/health'
    | '/board/$id'
    | '/board/live'
    | '/board'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/stats'
    | '/api/departures'
    | '/api/health'
    | '/board/$id'
    | '/board/live'
    | '/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  StatsRoute: typeof StatsRoute
  ApiDeparturesRoute: typeof ApiDeparturesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BoardIdRoute: typeof BoardIdRoute
  BoardLiveRoute: typeof BoardLiveRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departures': {
      id: '/api/departures'
      path: '/api/departures'
      fullPath: '/api/departures'
      preLoaderRoute: typeof ApiDeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/board/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/live': {
      id: '/board/live'
      path: '/board/live'
      fullPath: '/board/live'
      preLoaderRoute: typeof BoardLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  StatsRoute: StatsRoute,
  ApiDeparturesRoute: ApiDeparturesRoute,
  ApiHealthRoute: ApiHealthRoute,
  BoardIdRoute: BoardIdRoute,
  BoardLiveRoute: BoardLiveRoute,
  BoardIndexRoute: BoardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
